### ISSUE TITLE
CTD after talking with a random NPC in Nightingate Inn and asking to play a song (bard)

### ISSUE THREAD

**Issue by quidgy** [ForgottenGlory/Living-Skyrim-2#153] opened 2020-06-09 11:12 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_6_9_21-1-37.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4751732/Crash_2020_6_9_21-1-37.txt)

**LS Version**
2 Beta 4

**Describe the bug**
CTD after entering the Nightingate Inn. I spoke with an NPC there who offered to play a song with  me. The option had "(bard)" in it. After I selected the song, the game crashed.

**To Reproduce**
Tried it twice, crashed both times. 

**Expected behavior**
No crash
![ScreenShot253](https://user-images.githubusercontent.com/66656142/84141098-f83fc800-aa95-11ea-8542-f84a03ccf749.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Comment by tjbassoon** [comment] 2020-06-09 17:35
This is a duplicate of bug 96 https://github.com/ForgottenGlory/Living-Skyrim-2/issues/96

**Comment by ForgottenGlory** [comment] 2020-06-13 16:07
As mentioned, duplicate of #96

**Closed by ForgottenGlory** 2020-06-13 16:07 UTC
Labels: bug
