### ISSUE TITLE
we have another purple shield  

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#287] opened 2020-07-15 07:34 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS2 2.02

**Describe the bug**
missing textures on a shield when it is not out

**To Reproduce**
get the shield equip but do not have it out

**Expected behavior**
should look like what it does in inventory 
![ScreenShot272](https://user-images.githubusercontent.com/66355096/87516805-97328380-c643-11ea-9fa1-1c0176a78f41.png)
![ScreenShot271](https://user-images.githubusercontent.com/66355096/87516846-a4e80900-c643-11ea-9a69-9f19a4f26863.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment] 2020-07-18 15:25
Related to #255, closing this one so there's not multiple for the same bug

**Comment by ForgottenGlory** [comment] 2020-07-18 15:28
Reopened because the other one was fixed, not sure why this one isn't fixed also

**Comment by LaughingHyena279** [comment] 2020-07-20 09:20
I am getting this too, for a Viking shield with a different base texture than the one above. Mine is the Red Spiral variant.

**Comment by TwistedModding** [comment] 2020-07-28 14:15
I still think this is caused by allgud not generating something properly.

**Comment by Day7-J** [comment] 2020-07-28 15:51
Yeah, the unskinned shields is allgud mesh generation stuff
regenerating the meshes in sseedit using the allgud script on weaponsmerged.esp has completely fixed the textureless viking shields entirely while on your back
since it has custom textures you also need to run the textureexplosion script, and _that_ makes an esp containing the fixed bits; I have ESL'd a few things so the extra esp file doesn't effect me, but I'm sure there is a way to re-merge it all

**Comment by ForgottenGlory** [comment] 2020-07-29 18:26
Should be fixed 2.2.0

**Closed by ForgottenGlory** 2020-07-29 18:26 UTC
Labels: bug
