### ISSUE TITLE
Bard dialogue options with Ange the Song-Bearer cause CTD

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#96] opened 2020-06-03 23:53 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_6_3_19-31-55.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4726719/Crash_2020_6_3_19-31-55.txt)
[Crash_2020_6_3_19-42-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4726720/Crash_2020_6_3_19-42-6.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**
[bardctdsave.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4726722/bardctdsave.zip)

**LS Version**
Beta 2

**Describe the bug**
Ange has a (Bard) dialogue tree, after going through and selecting a song to play, Ange will idle for a few seconds and then CTD. Both options cause it for me.

**To Reproduce**
Speak to Ange the Song-Bearer in the Bannered Mare, select the (Bard) dialogue option and go through it.

**Expected behavior**
To play a song, I think.

**Screenshots**
![ScreenShot219](https://user-images.githubusercontent.com/63564258/83700073-cdf09500-a5d3-11ea-9962-6101fce8221d.png)

**Additional context**

**Comment by ForgottenGlory** [comment] 2020-06-04 18:05
Possibly fixed Beta 3, followup on this

**Comment by tjbassoon** [comment] 2020-06-08 22:42
Will test with beta 4.

**Comment by tjbassoon** [comment] 2020-06-09 01:47
Bug still exists. Tested by creating new character, let scripts finish, no MCM setup. Start in an inn, add Lute to inventory via console. Moveto.player to get to the NCP, initiated Bard dialog, CTD when she said "let me play it for you". I noticed the Lute moved to my back just before the CTD, so it might not be with the dialog, but something in ALGUD that causes the crash.

**Comment by quidgy** [comment] 2020-06-09 11:19
I just found this bug, sorry I lodged a duplicate of my own.

**Comment by ForgottenGlory** [comment] 2020-06-18 16:05
I have no idea what's causing this, I'm open to suggestions.

**Comment by tjbassoon** [comment] 2020-06-19 00:50
When this happens in a working LO (it works in Lexy's) a scripted animation forces the player/character to move to a set location in the inn, and then take out an instrument and animation+audio plays. My suspicion is that something like AGO is screwing with this behavior. My Lexy LO had iEquip running but not AGO. I'll test this again in Beta 5 and also test without AGO in the LO to see if that has anything to do with it.

**Comment by ForgottenGlory** [comment] 2020-06-23 19:31
I'm not able to find the cause of this, so for now I've just removed this option from her dialog list.

**Closed by ForgottenGlory** 2020-06-23 19:31 UTC
Labels: bug, followup, high priority
