### ISSUE TITLE
Shield issue when sheathed

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#137] opened 2020-06-07 05:14 UTC
My shield (Field Guard's Shield) appears to be on both my arm and back when sheathed. Does not appear to be a problem with other shields that I've had.

**To Reproduce**

Equip Field Guard's Shield (38000B1E). Unsheath and re-sheath weapon.

**Expected behavior**
Shield will appear both on your toons back and arm.

**Screenshots**
![ScreenShot246](https://user-images.githubusercontent.com/66503902/83960884-51123380-a8d1-11ea-9248-d9699548263f.png)

**Comment by ForgottenGlory** [comment] 2020-06-07 14:21
Duplicate of #87

**Closed by ForgottenGlory** 2020-06-07 14:21 UTC
Labels: bug
