### ISSUE TITLE
Purple image on shield when sheathed only

### ISSUE THREAD

**Issue by beefstock** [ForgottenGlory/Living-Skyrim-2#123] opened 2020-06-06 04:30 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS 2 Beta 2

**Describe the bug**
Shield is purple when sheathed only. 

**To Reproduce**
Equip shield and sheath it in 3rd person view

**Expected behavior**
Shield should have same texture as when equipped

**Screenshots**
![ScreenShot215](https://user-images.githubusercontent.com/50211938/83935967-0cc14f00-a77c-11ea-9003-73d3d7c98515.png)
![ScreenShot216](https://user-images.githubusercontent.com/50211938/83935972-134fc680-a77c-11ea-9d3d-0ce1ce551c72.png)

**Additional context**

**Comment by ForgottenGlory** [comment] 2020-06-06 04:36
Duplicate of #89, please check existing issues before reporting.

**Closed by ForgottenGlory** 2020-06-06 04:36 UTC
Labels: bug
