### ISSUE TITLE
Dragon Priest Masks appear to have vanilla enchantments instead of Reliquary of Myth's enchantments

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#265] opened 2020-07-10 07:36 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Ver. 2.01 

**Describe the bug**
The mask of Krosis still has its vanilla enchantment, instead of its enchantment from Reliquary of Myth

**To Reproduce**
Reloaded my save after acquiring Krosis several times, equipping and removing the mask each time. While a Master of Disguise prompt would fire when putting on the mask ("The Vigilants of Stendarr won't be happy") and removing it ("The Daedra won't be happy"), the mask retains its vanilla enchantment.

**Expected behavior**
The mask to have its enchantment from Reliquary of Myth

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot290](https://user-images.githubusercontent.com/67298916/87128891-47b81600-c245-11ea-9186-578b6fcdc00f.png)

**Additional context**
Of note is that I was also unable to learn Throw Voice from the Shearpoint Word Wall, which is where Krosis (the dragon priest) spawns. It's possible to hear chanting and a glow, but the wall will not teach a character Throw Voice no matter how close a character approaches it. I was forced to add the shout via console.

**Comment by PKYxReGiGiGaSx** [comment] 2020-07-10 07:40
That's because the DPM addon isn't being use for the guide for some odd reason.

**Comment by ForgottenGlory** [comment] 2020-07-13 21:32
Duplicate of #232

**Closed by ForgottenGlory** 2020-07-13 21:32 UTC
Labels: bug
