### ISSUE TITLE
Hedge Mage or S. Rorickstead CTD (I think its Hedge Mage)

### ISSUE THREAD

**Issue by JulesMarz** [ForgottenGlory/Living-Skyrim-2#269] opened 2020-07-10 19:39 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Crash_2020_7_10_20-3-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4905013/Crash_2020_7_10_20-3-47.txt)

[Save22_64BB1315_0_4B616C696D61_Tamriel_000353_20200710190308_6_1.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4905055/Save22_64BB1315_0_4B616C696D61_Tamriel_000353_20200710190308_6_1.txt)

**Change ".txt" to ".ess"**

**LS Version**
2.0.1

**Describe the bug**
After going to Rorickstead for the first time, the Hedge Mage quest appears. Go south of Rorickstead, CTD. 

**To Reproduce**
Steps to reproduce the behavior: see above, I have done this now on 2 fresh play through. (first was in ver 2.0.0)

I have gone through the same area south of rorickstead before first going to rorickstead, or the quest beginning, and it seemed fine.

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Expected behavior**
A clear and concise description of what you expected to happen. Not to CTD. 

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment] 2020-07-13 21:46
Duplicate of #248

**Closed by ForgottenGlory** 2020-07-13 21:46 UTC
Labels: bug
