### ISSUE TITLE
Orange circles around the light source for the lanterns of skyrim II mod while walking 

### ISSUE THREAD

**Issue by Soundtrack2chaos** [ForgottenGlory/Living-Skyrim-2#340] opened 2020-08-01 03:50 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
The version right before 2.2.0 

**Describe the bug**
As I walk by light poles at night, I see some sort of weird circle around the lamps as the LOD generates (I’m not sure if I am using the correct verbiage, but basically as I walk down and the game tries to show me more of the area I am walking towards). It only happens at night, happens for maybe a second or a half a second, but it happens frequently as you continue to walk. 

**To Reproduce**
Steps to reproduce the behavior: I believe it happens everywhere that has a light pole, but I’ve noticed it the most on the stretch of the road as you approach whiterun, because it has a ton of light poles there. 

**Expected behavior**
I expected to not see these circles around the lights as I walk through the area. I took off volumetric lights in my ENB and it still happens, so I’m not sure if there’s anything on my end that I can do to fix it. 

**Screenshots**
![A3263255-604D-40BC-8DCF-FBE9D2554BBD](https://user-images.githubusercontent.com/69066280/89093418-3b2c6680-d388-11ea-8155-8397b42e4670.png)

**Additional context**

**Comment by jokerstyle00** [comment] 2020-08-01 04:18
Also had this issue on 2.0.1 and 2.0.2

**Comment by ForgottenGlory** [comment] 2020-08-07 23:51
Does this still occur if you disable ENB? If so, did you make any changes to DynDOLOD?

**Comment by Soundtrack2chaos** [comment] 2020-08-08 02:22
> 
> 
> Does this still occur if you disable ENB? If so, did you make any changes to DynDOLOD?

It happens with and without the ENB i'm using (amon reborn). I have not made any changes to DynDOLOD (no personal familiarity with the program).

**Comment by jchritton** [comment] 2020-08-12 17:26
So this isn't unmodified LS2 (though likely nothing interfering with this issue), but I managed to find an area where this happens even up close (I believe it was on a road near Little Vivec). Feel free to ignore if not helpful with the extra mods, but might at least help go in the right direction.

![orangecircle-debug-1](https://user-images.githubusercontent.com/18075641/90046749-7edf7400-dc96-11ea-9392-0368e990a24f.png)

![orangecircle-debug-2](https://user-images.githubusercontent.com/18075641/90046753-8010a100-dc96-11ea-909c-b9a004bb49a2.png)

**Comment by TwistedModding** [comment] 2020-08-12 17:28
I have experienced this as well on unmodified versions of LS2. Looking online it might be something with lanterns of skyrim 2 and dyndolod

**Comment by PizzaSodebo** [comment] 2020-08-12 18:23
On the LE dyndolod needed a patch for the script between dyndo + LoS
Also, fake light child in the dyndo can make that on the city (specially Whiterun)

**Comment by cepritchard** [comment] 2020-08-25 22:40
I've got this as well.  Tried playing around in ENB settings but no change.

**Comment by ForgottenGlory** [comment] 2020-09-04 01:09
The author of Lanterns of Skyrim 2 is aware of the issue and is working on DynDOLOD compatibility (which is the cause of this issue). Should be fixed once that patch is available.

**Closed by ForgottenGlory** 2020-09-04 01:09 UTC
Labels: bug, question
