### ISSUE TITLE
Ebony Armor inconsistancy

### ISSUE THREAD

**Issue by combatmaster1o3** [ForgottenGlory/Living-Skyrim-2#312] opened 2020-07-21 07:25 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Mismatched Texture with Ebony Armor and it's helmet

**To Reproduce**
Look at Ebony Armor

**Expected behavior**
The texture to be consistent between set pieces.

**Screenshots**
Example images
![image](https://user-images.githubusercontent.com/67399578/88024861-6b127900-cb01-11ea-9b42-e24f47ca83c5.png)
![image](https://user-images.githubusercontent.com/67399578/88024999-a14ff880-cb01-11ea-839d-fbcbe4b38d4f.png)
![image](https://user-images.githubusercontent.com/67399578/88025539-6c907100-cb02-11ea-81c9-0a514e2574f7.png)
![image](https://user-images.githubusercontent.com/67399578/88081893-0d0c8280-cb4f-11ea-963c-73bbf2ed4a92.png)
![image](https://user-images.githubusercontent.com/67399578/88081982-28778d80-cb4f-11ea-9154-b8892f190f12.png)
![image](https://user-images.githubusercontent.com/67399578/88082034-3c22f400-cb4f-11ea-9158-3aec575ce3b4.png)
![image](https://user-images.githubusercontent.com/67399578/88082107-565cd200-cb4f-11ea-90df-0cfd5842a5c1.png)

**Additional context**
Minor issue, if anything states the general quality of Living Skyrim is so high that it makes something like this stick out. Now those fat fingers on the other hand....

**Comment by TwistedModding** [comment] 2020-07-21 15:01
Glory will need the items in question selected in console for them to get fixed.

**Comment by combatmaster1o3** [comment] 2020-07-21 16:32
On it

**Comment by ForgottenGlory** [comment] 2020-07-29 18:13
Duplicate of #310

**Closed by ForgottenGlory** 2020-07-29 18:13 UTC
Labels: bug
