### ISSUE TITLE
Steel Plate Helmet Invisible and hair aswell

### ISSUE THREAD

**Issue by SovnSkyrim** [ForgottenGlory/Living-Skyrim-2#140] opened 2020-06-07 15:50 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Character without helm: https://prnt.sc/svemys
Character with helm : https://prnt.sc/sven4n

**Comment by gooeymonster** [comment] 2020-06-07 17:57
It seems to be an issue with other close-faced helmets, like the Ebony Helmet as well

**Comment by ForgottenGlory** [comment] 2020-06-07 18:01
Duplicate of #62

**Closed by ForgottenGlory** 2020-06-07 18:01 UTC
Labels: bug
