### ISSUE TITLE
Floating Harlaug in Dawnstar Harbor

### ISSUE THREAD

**Issue by mepatterson** [ForgottenGlory/Living-Skyrim-2#172] opened 2020-06-13 19:39 UTC
**LS Version**
BETA 5

**Describe the bug**
Harlaug is just hanging out, reading his book in mid-air. Looks like he's sitting on a boat that isn't there?

**To Reproduce**
Go to Dawnstar. Check out the harbor. Find Harlaug.

**Expected behavior**
Guy is either not there, or he's sitting on a solid structure, like a boat.

**Screenshots**

![enb2020_6_13_14_14_46](https://user-images.githubusercontent.com/74207/84577631-a93eaf00-ad83-11ea-9ee2-0f5d025abffb.jpg)

**Comment by Dommius** [comment] 2020-06-13 19:49
I had that in LS4 as well, Just confirming it's still happening.

**Comment by mepatterson** [comment] 2020-06-13 19:51
Yeah I just installed and fired up beta 5 and created a new char shipwrecked off Dawnstar coast. So def happening for me.

**Comment by ForgottenGlory** [comment] 2020-06-18 15:45
Possibly fixed Beta 6, followup on this

**Comment by mepatterson** [comment] 2020-06-18 20:05
Just loaded up Beta 6, went to Dawnstar. Harlaug still floating in the air, reading his book.

**Comment by Ajexais** [comment] 2020-06-18 21:57
I had this bug in Beta 3

**Comment by Capzien** [comment] 2020-06-22 08:39
He's still floating in Beta 6
![ScreenShot266](https://user-images.githubusercontent.com/66503902/85266731-a6486a80-b4b7-11ea-8b9f-c17564633dfc.png)

**Comment by tjbassoon** [comment] 2020-06-22 16:09
Looks to me the issue is really that there should be a deck/dock or something with a chair for him to be sitting on that was removed in one of the patches maybe.

**Comment by ForgottenGlory** [comment] 2020-06-23 18:21
Should be fixed Beta 7

**Closed by ForgottenGlory** 2020-06-23 18:21 UTC
Labels: followup, low priority, minor bug
