### ISSUE TITLE
Darkwater Crossing: Floating Items/Clipping/ and Moving Texture???

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#120] opened 2020-06-05 02:55 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.
Newest Beta Release
**Describe the bug**
Floating Items/Clipping/ and Moving Texture. The moving texture is atop the tower and moves with you walking around the screenshots of the stone tower shows different textures on the same piece of brick as I moved around.
**To Reproduce**
Visit Darkwater Crossing
**Expected behavior**
No floating items, clipping, or moving textures
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200604191122_1](https://user-images.githubusercontent.com/62521502/83831867-2475d600-a69d-11ea-9b90-cfa3e210244b.jpg)
![20200604191124_1](https://user-images.githubusercontent.com/62521502/83831874-28095d00-a69d-11ea-94d4-41d25b884455.jpg)
![20200604191127_1](https://user-images.githubusercontent.com/62521502/83831879-2a6bb700-a69d-11ea-8f64-041da339f92c.jpg)
![20200604191129_1](https://user-images.githubusercontent.com/62521502/83831881-2cce1100-a69d-11ea-99ef-fa163b9060bc.jpg)
![20200604191517_1](https://user-images.githubusercontent.com/62521502/83831891-2fc90180-a69d-11ea-83de-892b926d00b1.jpg)
![20200604191525_1](https://user-images.githubusercontent.com/62521502/83831896-322b5b80-a69d-11ea-9d13-adb0718027f5.jpg)
![20200604191658_1](https://user-images.githubusercontent.com/62521502/83831904-36577900-a69d-11ea-887a-d3faf300e8af.jpg)
![20200604191701_1](https://user-images.githubusercontent.com/62521502/83831908-39526980-a69d-11ea-84f1-2355e3639d75.jpg)
![20200604191703_1](https://user-images.githubusercontent.com/62521502/83831969-6141cd00-a69d-11ea-8b11-ee940e0b37e1.jpg)

**Comment by ForgottenGlory** [comment] 2020-06-05 02:57
Duplicate of #107 , fixed Beta 3.

**Closed by ForgottenGlory** 2020-06-05 02:57 UTC
Labels: bug
