### ISSUE TITLE
Cougar spawned at start of game

### ISSUE THREAD

**Issue by Arathrax** [ForgottenGlory/Living-Skyrim-2#399] opened 2020-08-23 16:37 UTC
Alternate started at Sleeping Giant Inn
Right outside (in town) a cougar was there, and attacked several townspeople (maybe related to Animallica or Skytest)

**Comment by ForgottenGlory** [comment] 2020-08-24 03:50
Duplicate of #404

**Closed by ForgottenGlory** 2020-08-24 03:50 UTC
